apiVersion: batch/v1
kind: Job
metadata:
  name: zarf-initializer
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: zarf-initializer
      containers:
      - name: zarf-initializer
        image: ghcr.io/leppek/zarf-initializer:v0.84.0
      restartPolicy: OnFailure
